spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:order_master
    driver: org.h2.Driver
    username: postgres
    password: holy@1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
