global:
  message: Welcome to order service prod environment!!
server:
  port: 9095
message: Hello from Prpduction!
spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/order_prod
    username: postgres
    password: holy@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
