global:
  message: Welcome to order service dev environment!!
server:
  port: 9094
message: Hello from Dev!
spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/order_dev
    username: postgres
    password: holy@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
